dist: bionic

sudo: required

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - ./travis_before_install.sh

jobs:
  include:
    - stage: build docker image
      script:
      - sudo ./build-image.sh
