dist: xenial

sudo: required

before_install:
  - ./travis_before_install.sh


jobs:
  include:
    - stage: build docker image
      script:
      - sudo cat /etc/docker/daemon.json
      - docker version
      - docker version -f '{{.Server.Experimental}}'
      - sudo ./build-image.sh
