dist: bionic

arch:
  - amd64
  - arm64

addons:
  apt:
    sources:
      - docker-bionic

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - sudo ./travis_before_install.sh

jobs:
  include:
    - stage: build docker image
      script:
      - sudo ./build-image.sh
